name: Samgayton
favicon: null
layout_spectrum: 0.56664
typography_spectrum: 0.4538
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: "Sam Gayton, Children's Author"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1F1955'
    - '#FFFFFF'
    - '#5C99D1'
    - '#9AC6EA'
    - '#909090'
  brandStrength: 0.625
  lightness: 0.625
  saturation: 1
  rhythmicContrast: 0
purpose: []
