layout_spectrum: 0.1458685
typography_spectrum: 0.1003373
color:
  lightness: 0.3752108
  brandStrength: 0.6315346
  saturation: 0.5826307
  rhythmicContrast: 0.5876897
  brandColors:
    - '#1F1955'
    - '#FFFFFF'
    - '#5C99D1'
    - '#9AC6EA'
    - '#909090'
name: Samgayton
