name: Samgayton
favicon: null
layout_spectrum: 0
typography_spectrum: 0.73678
title: "Sam Gayton, Children's Author"
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#9f9f9f'
    - '#bfbfbf'
    - '#7d7d7d'
    - '#575757'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
